# Generated by Django 3.0.8 on 2020-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='file',
            field=models.FileField(upload_to='', verbose_name='arquivo'),
        ),
    ]
