# Generated by Django 3.0.8 on 2020-07-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_auto_20200723_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='file',
            field=models.FileField(upload_to='', verbose_name='processos.csv'),
        ),
    ]
