# Generated by Django 3.0.8 on 2020-07-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0005_cadastro_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='file',
            field=models.FileField(upload_to='processo', verbose_name='processos.csv'),
        ),
    ]
