# Generated by Django 3.0.8 on 2020-07-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0007_remove_cadastro_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
